### ISSUE TITLE
Can't seem to use it in Android

### ISSUE THREAD

**Issue by nbastoWM** [corymsmith/react-native-icons#152] opened 2015-12-11 09:21 UTC
In iOS all goes fine but in Android when I run the app it shows me the error screen:

```
TypeError: expected dynamic type 'boolean', but had type 'int64' (constructing arguments for RCTNetworking.sendRequest at argument index 5)
```

![screen shot 2015-12-11 at 09 20 12](https://cloud.githubusercontent.com/assets/15138821/11740151/7f7bb918-9fe8-11e5-8a4c-30fdf64e4a2f.png)

and in the logs:

```
--------- beginning of /dev/log/system
W/ReactNativeJS( 1346): 'Warning: Native component for "RCTModalHostView" does not exist'
W/ReactNativeJS( 1346): '`ProgressBarAndroid` has no propType for native prop `AndroidProgressBar.progress` of native type `number`'
```

The build goes
I have RN 0.15 and when I tried to upgrade to 0.16 there was too much hassle regarding dependencies so I had to rollback.

**Comment by nbastoWM** [comment] 2015-12-11 11:49
I got it working by changing the version to 0.6.3.
Isn't 0.7 compatible with RN 0.15?

**Comment by corymsmith** [comment] 2015-12-11 13:07
Did you update your gradle files React dependency?

**Comment by nbastoWM** [comment] 2015-12-11 13:52
I did as instructed in the "Getting started - Android".

**Comment by corymsmith** [comment] 2015-12-11 13:55
Errors like this are usually caused by the Java code and he code getting out of
sync. What version of RN is in your gradle file and what version of RN is in
your package.json.

**Comment by nbastoWM** [comment] 2015-12-14 13:43
In package json I have
"react-native": "^0.15.0",

in build.gradle I have:
compile "com.facebook.react:react-native:0.15.+"

Should I specify "0.15.0" and react-native:0.15.0 ?

**Comment by corymsmith** [comment] 2015-12-14 14:16
Either should work. Are you still getting the same error?

**Comment by jawadrehman** [comment] 2015-12-14 16:25
i have the same issue @corymsmith

**Comment by corymsmith** [comment] 2015-12-14 21:41
@jawadrehman What error are you getting? Also, what version of React Native is in your package.json file & gradle file. And what version of this library?

**Comment by corymsmith** [comment] 2015-12-14 22:11
I would highly recommend updating to 0.16.0. The error above doesn't seem like it has anything to do with this project. The example project uses 0.16.0 and works great

**Comment by jawadrehman** [comment] 2015-12-15 11:55
@corymsmith i tried updating to version 16  i got a bunch of other errors about something with UndefinedView . 
so had to downgrade to 0.15

**Comment by jawadrehman** [comment] 2015-12-15 11:56
i will try to upgrade and resolve the issues.

**Comment by corymsmith** [comment] 2015-12-18 15:37
@jawadrehman @nbastoWM Did you end up sorting this out? I'm hoping to close this issue since I'm fairly certain its not related to this project.

**Comment by nbastoWM** [comment] 2015-12-21 17:38
I'm using 0.6.3. I guess 0.7 requires RN 0.16. 
Version 0.6.3 seems to work fine for me.
Thanks.

**Closed as completed** 2015-12-21 20:29 UTC

**Comment by jawadrehman** [comment] 2015-12-22 10:32
@corymsmith version 0.7 worked fine with 0.16
