### ISSUE TITLE
Cannot install react-native-icons in my existing project

### ISSUE THREAD

**Issue by billyshena** [corymsmith/react-native-icons#6] opened 2015-04-06 17:21 UTC
Hello guys, I've tried to setup react-native-icons following the installation guide on github, however my build fails with some errors like (RCTRootView.h , RCTViewManager.h not found)
I've also tried to clone the example and run it on my device but still errors appear when I try to build in xCode.

Any ideas?

Thanks in advance !

**Comment by corymsmith** [comment] 2015-04-06 17:25
Hey @billyshena, that usually means the that the ReactNativeIcons project can't see the React Native headers, have you done Step 6 in the instructions?

**Comment by billyshena** [comment] 2015-04-06 17:30
Thanks for your quick reply @corymsmith 
I've followed each step described in the installation guide.
Here is a screenshot of my xCode settings on the 6th step: http://imgur.com/bwigjbp

Best,

**Comment by chadobado** [comment] 2015-04-06 20:22
I'm currently having the same problem

**Comment by chadobado** [comment] 2015-04-06 20:28
Currently having the same or similar problem.  

Possibly also as mentioned [here](https://github.com/corymsmith/react-native-icons/issues/5#issuecomment-90167867).

```
(null): error: /Users/Chad/Library/Developer/Xcode/DerivedData/ToyTime-dlspuucbonmitigximwovpmsceuh/Build/Products/Debug-iphonesimulator/ReactNativeIconsResources.bundle: No such file or directory

```

Full log:

```
CpResource /Users/Chad/Library/Developer/Xcode/DerivedData/ToyTime-dlspuucbonmitigximwovpmsceuh/Build/Products/Debug-iphonesimulator/ReactNativeIconsResources.bundle /Users/Chad/Library/Developer/Xcode/DerivedData/ToyTime-dlspuucbonmitigximwovpmsceuh/Build/Products/Debug-iphonesimulator/ToyTime.app/ReactNativeIconsResources.bundle
    cd /Users/Chad/Documents/ToyTime/ToyTime
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/Chad/Library/Developer/Xcode/DerivedData/ToyTime-dlspuucbonmitigximwovpmsceuh/Build/Products/Debug-iphonesimulator/ReactNativeIconsResources.bundle /Users/Chad/Library/Developer/Xcode/DerivedData/ToyTime-dlspuucbonmitigximwovpmsceuh/Build/Products/Debug-iphonesimulator/ToyTime.app

error: /Users/Chad/Library/Developer/Xcode/DerivedData/ToyTime-dlspuucbonmitigximwovpmsceuh/Build/Products/Debug-iphonesimulator/ReactNativeIconsResources.bundle: No such file or directory
```

Assuming not the cause, but noticed that installation instructions differed slightly:

```
3. Go to node_modules ➜ react-native-icons and add ReactNativeIcons.xcodeproj
```

node_modules/react-native-icons/ReactNativeIcons.xcodeproj (does not exist)
node_modules/react-native-icons/ios/ReactNativeIcons.xcodeproj (does exist)

**Comment by chadobado** [comment] 2015-04-06 20:37
Attempting again from scratch now gets me to the same issue as @billyshena 

```
/Users/Chad/Documents/ToyTime/ToyTime/node_modules/react-native-icons/ios/IconTabBarItem/SMXTabBarManager.h:1:9: 'RCTViewManager.h' file not found
```

Edit: 

Accidentally added the `User Header Search Paths` to the project and not to `ReactNativeIcons.xcodeproj` as in instructions.

Now fixed results in the original `ReactNativeIconsResources.bundle: No such file or directory` error mentioned above.

**Comment by corymsmith** [comment] 2015-04-06 21:02
@chadobado @billyshena Can you try to drag ReactNativeIconsResources.bundle into the Copy Bundle Resources build phase of the ReactNativeIcons project as well? I'll have to update the Readme and the install process to clarify things a bit

**Comment by chadobado** [comment] 2015-04-06 21:25
Great, that fixed it.  Thanks for the quick reply @corymsmith

**Comment by corymsmith** [comment] 2015-04-06 21:25
@chadobado Ok awesome, I'll update the readme

**Comment by billyshena** [comment] 2015-04-06 21:48
EDIT: Now everything builds successfully ( I had to set Location: Absolute Path in xCode project => 'Identity and Type' panel.
However, I get an error "requiring unknown module FAKIconImage" using the example code here: https://github.com/corymsmith/react-native-icons/blob/master/Example/index.ios.js

Any ideas?

Thanks !

**Comment by dmnkgrc** [comment] 2015-04-06 22:26
I have the same issue as @billyshena, the absolute path fixed the building problem but I get the same error.

**Comment by corymsmith** [comment] 2015-04-06 23:10
@billyshena @dominikgar Did you install via NPM? That error typically occurs if the JS files aren't found in node_modules in the root of your project

**Comment by dmnkgrc** [comment] 2015-04-06 23:28
@corymsmith yes I did

**Comment by billyshena** [comment] 2015-04-07 07:23
@corymsmith : Yes, installed via NPM but does not resolve the issue.
After setting the absolute path, the builds is still failing but no errors.

**Comment by badmonster0** [comment] 2015-04-08 04:26
i had the same issue in the first place, make sure the path was set to "recursive" resolved the problem for me. 
(you want to double click on the path , and choose recursive)

Hope this helps

**Comment by billyshena** [comment] 2015-04-08 09:22
I've set also the option on recursive but that did not change anything.

Billy,

**Comment by JonasJonny** [comment] 2015-04-12 22:46
I also had to set the location to something else than "default".
From "relative to group" to "relative to project". I don't know why but it helps me to fix build error with "***.bundle".

**Comment by corymsmith** [comment] 2015-04-12 22:53
I'm working on an update with support for react-native 0.3.11 and also reverting back to just including the font files in your bundle vs. Including a .bundle file. This will also allow you to only include the fonts you use in your app vs. bloating the binary size with icon fonts you aren't using.

**Comment by leecade** [comment] 2015-04-13 21:19
:+1:

**Comment by corymsmith** [comment] 2015-04-14 16:14
New version (0.0.2) is published to NPM, I've updated the install instructions as well.

**Closed as completed by corymsmith** 2015-04-14 16:14 UTC
