### ISSUE TITLE
Question: How to change color for "inactive" tab item?

### ISSUE THREAD

**Issue by JonasJonny** [corymsmith/react-native-icons#21] opened 2015-04-21 16:55 UTC
Hello,
I couldn't find a way how to change default text color (gray) to white or anything. Background for active/inactive tab will be nice feature too.
But text is really important because when I will change "barTintColor" then gray looks really bad.
For active tab "tintColor" is working as expected.
Styles are also not working.

Thank you for any help.

**Comment by JonasJonny** [comment] 2015-04-29 19:52
I can change text color through Objective-C.

``` javascript
// Add this code to change StateNormal text Color,
[UITabBarItem.appearance setTitleTextAttributes:
@{NSForegroundColorAttributeName : [UIColor colorWithRed:0.424 green:0.29 blue:0.529 alpha:1]}
forState:UIControlStateNormal];

// then if StateSelected should be different, you should add this code
[UITabBarItem.appearance setTitleTextAttributes:
@{NSForegroundColorAttributeName : [UIColor whiteColor]}
forState:UIControlStateSelected];
```

But I can't find where you generate images from icon fonts to change default image color
http://stackoverflow.com/questions/22767098/how-to-change-inactive-icon-text-color-on-tab-bar

---

This feature would be really helpful if we change barTintColor.

**Comment by corymsmith** [comment] 2015-04-29 20:17
Are you thinking this should be a property on my tab bar implementation? Are you wanting the text color to match the icon or allow them to be styled separately?

**Comment by JonasJonny** [comment] 2015-04-29 20:30
- Definitely it should be in SMXTabBar implementation
- I think there should be at least SMXTabBar property to change "Inactive tab" text or icon color
- It doesn't matter if icon color will follow text color or text color will follow icon color
- As you can see the stackoverflow link above. If you change barTintColor to blue then grey text is no longer good color. I found out I can change the bar text color as you can see above (I know it is not a great way but it works at least). But there is no way how to change icon color and remains grey :(.

**Comment by JonasJonny** [comment] 2015-04-29 20:43
This is the best result which I can achieve.
![tabbar](https://cloud.githubusercontent.com/assets/1771823/7400885/4796213e-eec0-11e4-8270-95f20ee05e0f.jpg)

inactive violet text is [UIColor colorWithRed:0.424 green:0.29 blue:0.529 alpha:1] or #6c4a87

There should be at least SMXTabBar implementation to color the unselected icons to different color than iOS native grey. But it makes sense to change also the unselected tab text color. Separately or together doesn't matter.

**Comment by corymsmith** [comment] 2015-04-29 21:06
Yeah I see what you mean, the issue is that the underlying native tab bar doesn't have a way to specify the unselected icon color unless you use separate images for each state. I've tried a few things but will have to dig a bit deeper to see how we can fully solve this. If you have any thoughts on implementation or get it working feel free to send over a Pull Request

**Comment by JonasJonny** [comment] 2015-04-29 21:51
Unfortunately I don't have enough iOS skills to solve this problem alone.
I don't know if you generate image from icon font to use it as active state or how is it possible to change the icon color through tintColor. I tried to change some values in "createImageForIcon" (IconGenerator.m) or in "FAKIconImageManager.m" but without luck. Maybe if the "new property" is set you can call another function to generate and use two images for normal state and selected state. If not use the current code. But I don't know how this could be difficult. 
Maybe this could help you somehow http://jslim.net/blog/2014/05/05/ios-customize-uitabbar-appearance/.

**Comment by meric426** [comment] 2015-05-18 21:36
+1

**Comment by KFoxder** [comment] 2015-07-14 23:49
+1

**Comment by sunnylqm** [comment] 2015-07-23 09:30
@corymsmith   http://stackoverflow.com/questions/26551458/change-tintcolor-of-unselected-uitabbarcontroller-item-title-and-background-imag  This answer from SO solved the problem.    (UIControlStateNormal, UIControlStateSelected and UIImageRenderingModeAlwaysOriginal) . Please check it out.

**Comment by jorgenskogmo** [comment] 2015-12-05 08:35
Is this happening?

**Comment by corymsmith** [comment] 2015-12-10 14:03
@baseio Haven't had time to implement  yet, would love a PR since lots of people have asked for it.

**Comment by ka05** [comment] 2016-01-21 22:10
Just in case someone needs this in swift
UITabBarItem.appearance().setTitleTextAttributes([NSForegroundColorAttributeName : UIColor.blueColor()], forState: UIControlState.Normal) // changes the default color
UITabBarItem.appearance().setTitleTextAttributes([NSForegroundColorAttributeName : UIColor.blackColor()], forState: UIControlState.Selected) // changes the selected color

**Comment by corymsmith** [comment] 2016-01-24 17:44
Closing this as support for this library is being discontinued, I highly recommend using https://github.com/oblador/react-native-vector-icons instead as its more fully featured, I've added a warning to the Readme about this as well.

**Closed as completed by corymsmith** 2016-01-24 17:44 UTC
Labels: enhancement, help wanted
