### ISSUE TITLE
[Icon] Zocial icons are cropped

### ISSUE THREAD

**Issue by elisei-timofte** [corymsmith/react-native-icons#139] opened 2015-11-17 15:06 UTC
I want to use some social fonts and what I get is this:
<img width="336" alt="screen shot 2015-11-17 at 5 01 51 pm" src="https://cloud.githubusercontent.com/assets/6162068/11215067/1bb15878-8d4d-11e5-8ca6-c8f8650956e5.png">

but in xcode I see that facebook, twitter and other guys looks good. Am I doing something wrong?

<img width="671" alt="screen shot 2015-11-17 at 5 03 26 pm" src="https://cloud.githubusercontent.com/assets/6162068/11215077/265519a4-8d4d-11e5-842f-1f170ac0cd43.png">

``` javascript
var items = ['facebook', 'twitter', 'googleplus', 'reddit', 'tumblr', 'stumbleupon']
items.map((item) => {
          return (
            <TouchableOpacity
              key     = {JSON.stringify(item)}
              <Icon
                name  = {`zocial|${item}`}
                size  = {35}
                color = 'Gray'
                style = {{width: 35, height: 35}}
              />
            </TouchableOpacity>
          )
        })
```

**Comment by corymsmith** [comment] 2015-11-17 19:16
There's a known issue for icons that are not square; I haven't had any time to dig into it though, PR's are always appreciated.

**Comment by corymsmith** [comment] 2015-12-06 20:34
This is a duplicate of #55

**Closed as completed by corymsmith** 2015-12-06 20:34 UTC
